services:
  - type: web
    name: assignment-tracker-spring
    runtime: docker
    plan: free
    rootDir: backend-spring
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
    healthCheckPath: /api/assignments
    autoDeploy: true
